# This is a basic workflow that is manually triggered

name: Manual bicep deploy workflow
env:
  location: eastasia
on:
  workflow_dispatch
  
jobs:
  bicepbuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: bicep  
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure CLI install bicep
        uses: Azure/cli@1.0.4
        with:
         inlineScript: az bicep install
         
      - name: Azure CLI build bicep
        uses: Azure/cli@1.0.4
        with:
         inlineScript: az bicep build --files main.bicep
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: bicep
      
    steps:
      - uses: actions/checkout@v2
      # Log into Azure
      - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS  }}

      # Deploy ARM Template
      - name: Deploy bicep via cli deploy
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create -f main.bicep -l ${{env.location}} --parameters location=${{env.build_name}}
 
